### ISSUE TITLE
rvm::system does not install default ruby

### ISSUE THREAD

**Issue by genslein** [sous-chefs/chef-rvm#259] opened 2014-04-15 17:03 UTC
The rvm::system recipe does not actually install the default Ruby listed in the attributes and rvm is not accessible as its path has not been added to the PATH environment variable

**Comment by alambike** [comment] 2015-01-10 10:13
I can confirm that #285 isn't resolving the issue. I have to explicitly set a node attribute 
```
{"rvm": {"install_rubies" : true }}
``` 
for chef run installs ruby. Maybe the attribute should be setted to true by default in attributes default file.

**Comment by alambike** [comment] 2015-01-11 03:09
I just send this PR #294 to set the default value to `install_rubies` attribute.

**Comment by damacus** [comment] 2019-05-31 20:22
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed by damacus** 2019-05-31 20:22 UTC
Labels: Bug, PR Submitted
